project 'inventoryApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inventoryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for inventoryApp

  target 'inventoryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'inventoryApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for inventoryApp-tvOS

  target 'inventoryApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
